object RoomFilterForm: TRoomFilterForm
  Left = 0
  Top = 0
  BorderStyle = bsNone
  Caption = 'RoomFilterForm'
  ClientHeight = 259
  ClientWidth = 276
  Color = clNavy
  TransparentColor = True
  TransparentColorValue = clNavy
  DoubleBuffered = True
  Font.Charset = ANSI_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = #44404#47548
  Font.Style = []
  KeyPreview = True
  OldCreateOrder = False
  OnClick = FormClick
  OnDeactivate = FormDeactivate
  OnKeyUp = FormKeyUp
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = 1
    Top = 1
    Width = 273
    Height = 257
    BevelOuter = bvNone
    Caption = 'Panel1'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = #45208#45588#44256#46357
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 0
    object RoomGrid: TStringGrid
      Left = 0
      Top = 0
      Width = 273
      Height = 257
      Align = alClient
      BorderStyle = bsNone
      ColCount = 1
      DefaultColWidth = 270
      DefaultRowHeight = 36
      DefaultDrawing = False
      FixedCols = 0
      RowCount = 10
      FixedRows = 0
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = #45208#45588#44256#46357
      Font.Style = []
      Options = [goFixedVertLine, goFixedHorzLine, goVertLine, goHorzLine, goDrawFocusSelected]
      ParentFont = False
      ScrollBars = ssNone
      TabOrder = 0
      OnClick = RoomGridClick
      OnDrawCell = RoomGridDrawCell
      OnKeyDown = RoomGridKeyDown
      OnKeyUp = RoomGridKeyUp
      OnMouseWheelDown = RoomGridMouseWheelDown
      OnMouseWheelUp = RoomGridMouseWheelUp
    end
  end
  object ApplicationEvents1: TApplicationEvents
    OnDeactivate = ApplicationEvents1Deactivate
    Left = 80
    Top = 111
  end
end
