import { Inter } from "next/font/google";
import "./globals.css";
import Navlayout from "./NavLayout";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <div className="bodyMain">
        <Navlayout/>
        {children}
      </div>
      </body>
    </html>
  );
}
